*&---------------------------------------------------------------------*
*& Report ZSD_VAL_PDF_PEDIDOS_ALV
*&---------------------------------------------------------------------*
* PROGRAMA    : ZSD_VAL_PDF_PEDIDOS_ALV                                *
* DESCRIPCION : validación de PDF's Asociados a Pedidos                *
* MODULO      : SD                                                     *
* FUNCIONAL   : Hector Adrian Cardenas Camacho                         *
* AUTOR       : Hector Adrian Cardenas Camacho                         *
* FECHA       : 02.12.2024
*&---------------------------------------------------------------------*
REPORT ZSD_VAL_PDF_PEDIDOS_ALV.


INCLUDE ZSD_VAL_PDF_PEDIDOS_ALV_TOP.
INCLUDE ZSD_VAL_PDF_PEDIDOS_ALV_SEL.
INCLUDE ZSD_VAL_PDF_PEDIDOS_ALV_CLS.
INCLUDE ZSD_VAL_PDF_PEDIDOS_ALV_MAI.
INCLUDE ZSD_VAL_PDF_PEDIDOS_ALV_PBO.
INCLUDE ZSD_VAL_PDF_PEDIDOS_ALV_PAI.
INCLUDE ZSD_VAL_PDF_PEDIDOS_ALV_F01.
